# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_game.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.StartButton = QtWidgets.QPushButton(self.centralwidget)
        self.StartButton.setGeometry(QtCore.QRect(650, 200, 120, 25))
        self.StartButton.setObjectName("StartButton")
        self.P1_score_label = QtWidgets.QLabel(self.centralwidget)
        self.P1_score_label.setGeometry(QtCore.QRect(650, 100, 120, 50))
        self.P1_score_label.setObjectName("P1_score_label")
        self.P2_score_label = QtWidgets.QLabel(self.centralwidget)
        self.P2_score_label.setGeometry(QtCore.QRect(650, 150, 120, 50))
        self.P2_score_label.setObjectName("P2_score_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.StartButton.setText(_translate("MainWindow", "Start!!!"))
        self.P1_score_label.setText(_translate("MainWindow", "Player1 scores:"))
        self.P2_score_label.setText(_translate("MainWindow", "Player2 scores:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
